// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddedcyoqmhccmnmcvyte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZWRjeW9xbWhjY21ubWN2eXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTc1MTUsImV4cCI6MjA3MTQ5MzUxNX0.NYeKvIhbbt1sG-qvboX78YmDhZ7T0EtalSTNbV4V-Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});